import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import Nav, { NavLink } from "./_components/nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("bg-background min-h-screen font-sans antialiased",geistSans.variable)}
      >
        <Nav>
          <NavLink href={"/"}>Dashboard</NavLink>
          {/* <NavLink href={"/products"}>All Products</NavLink> */}
          <NavLink href={"/products/new"}>New Product</NavLink>
          <NavLink href={"/products/manage"}>Manage Products</NavLink>
        </Nav>
        {children}
      </body>
    </html>
  );
}
